version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails/sample
permissions:
   - object: /var/www/
     pattern: "**"
     mode: 775
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  BeforeInstall:
      - location: scripts/BeforeInstall.sh
        timeout: 300
        runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 300
      runas: root
