version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/rails/sample
permissions:
   - object: /var/www/
     pattern: "**"
     owner: ec2-user
     mode: 775
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: scripts/clean.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/bundle_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
